### PR TITLE
Merge 3 features

### PR DESCRIPTION
**Pull request by tenerhades**
@davidparsson, I know you're short on time. This is just a merge of the others. Namely,

This PR adds the following features and bugs
--
- The ability to drag on links and images (and other objects) with any mouse button
  - Form input objects not supported (input, textarea, select tags, etc. including checkboxes and both "buttons" on Google's homepage)
  - If using Left Mouse Button and dragging on links are both enabled, then **the links won't work at all** (intermittently, that is; this is currently the only thing I'm interested in fixing).

- The ability to temporarily disable the extension by left-clicking its icon in the extension bar. The icon changes its image to show its current state.

- A right-click context menu option to add the current site to the Scrollbar Anywhere blacklist
  - If this extension's options page is open in another tab, then the setting will not take effect if the blacklist field is changed before that tab is closed.

### CODE REVIEW

**Comment by davidparsson** [comment]
I just wanted to let you know that I haven't forgotten about this, I'll hopefully get to reviewing it in the coming week.

**Comment by davidparsson** [comment]
@tenerhades, does this PR contain anything that's not included in the other three? I prefer to review and merge them separately, since it's easier to review smaller code changes.

**Comment by tenerhades** [comment]
No, it's just a merge of the other 3 as they were submitted in their individual pull requests. There were a couple of code conflicts, mainly in background.js, IIRC. I was just trying to save you that work with this one. Feel free to close/delete this one if you're going to review and possibly merge them individually.

**Comment by davidparsson** [comment]
Closing this in favor of #66 and #69.

**Pull request closed without merging**
